### ISSUE TITLE
Download for WPF .NET Core 3.1

### ISSUE THREAD

**Issue by tildebox** [hardcodet/wpf-notifyicon#29] opened 2020-05-06 15:49 UTC
I don't know how to download the newest version for WPF .NET Core 3.1

The version on NuGet was "Last updated" on 4/2/2016.

Can the whole code be placed in just one folder? I don't want to lose my overview.

**Comment by Lakritzator** [comment] 2020-05-06 16:53
It hasn't been released yet.

**Comment by tildebox** [comment] 2020-05-06 17:15
If I "Download ZIP" from https://github.com/hardcodet/wpf-notifyicon, you mean, the downloaded code do not have the closed ".Net Core 3.0 support" issue?

If the downloaded code have the ".Net Core 3.0 support" I just can switch to ".Net Core 3.0".

If no, is there a timeline? Why the code is not public?

**Comment by Lakritzator** [comment] 2020-05-06 18:47
The issue is not closed, the merge hasn't been done yet and we didn't build & publish the nuget package yet.
The code is public, you can see my pull-request here: https://github.com/hardcodet/wpf-notifyicon/pull/21

Just be patient, it will come.

**Comment by hyllus** [comment] 2020-07-22 20:03
It appears that the PR linked above has been merged, is there a timeline for when a new build might be published?

**Comment by Lakritzator** [comment] 2020-07-23 10:17
The fact that it was merged, unfortunately doesn't mean it works. There is an issue with it.

Due to corona I have practically 0 free time available for this (kid, job, other projects which actually provide me money), so it will come when it comes... sorry, you will just need to be patient.

**Comment by hyllus** [comment] 2020-07-23 16:58
Understandable.  Is there a particular issue in the issues list that you are referring to?  It'd be good to know what isn't working (and perhaps I could take a stab at fixing it).

**Comment by Lakritzator** [comment] 2020-08-05 11:50
@hyllus The issue was time, and also that I have some problems with my laptop... working from an old one now, which doesn't really motivate.

I fixed the biggest issue, it had to do with this: https://github.com/dotnet/msbuild/issues/4704
Very annoying... Anyway, I will need to go through some other issues and we must have a release soon.

**Comment by punker76** [comment] 2020-11-23 11:05
This will be available with next release (v1.1.0), coming hopefully soon.

**Closed by punker76** 2020-11-23 11:05 UTC
Labels: Enhancement
