### ISSUE TITLE
Bug: TrayMouseDoubleClick event not working correctly on TaskbarIcon

### ISSUE THREAD

**Issue by henon** [hardcodet/wpf-notifyicon#90] opened 2023-01-16 14:13 UTC
### Observation:

If you don't want to use a popup and instead want to wire the `TrayMouseDoubleClick` event directly this doesn't work. The event is somehow **only fired after a right click follows the double click**. 

### What should happen instead:

On left mouse double click the `TrayMouseDoubleClick` event should be invoked. 

### Workaround

Until this is fixed there is a workaroud: Add a popup to the resources ...

```xaml
            <Popup x:Key="Popup" Opened="OnPopupOpened">
                <Label>Popup for Dbl Click workaround due to bug</Label>
            </Popup>
```

... which opens correctly on left mouse double click. In the `Opened` event of that popup ...

```c#
        private void OnPopupOpened(object sender, EventArgs e)
        {
            var popup = sender as Popup;
            popup.IsOpen = false;
            OnTrayDoubleClick(this, new RoutedEventArgs());
        }
```

... we can execute our double click handler.

**Comment by punker76** [comment] 2024-10-07 14:42
I can't reproduce this with the latest dev code, so I will close this until it will appear again.

**Closed by punker76** 2024-10-07 14:42 UTC
