### ISSUE TITLE
System Tray getting Minimized

### ISSUE THREAD

**Issue by SVishC** [hardcodet/wpf-notifyicon#14] opened 2019-08-01 05:21 UTC
The System tray getting minimized when mouse pointer is moved to a different position.But the Context menu remains,which is not the default behavior of Windows NotifyIcon. Please fix this ASAP.

**Comment by Lakritzator** [comment] 2019-08-02 07:21
I tried the example here: https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.notifyicon?view=netframework-4.8

I actually cannot reproduce what you describe, so I must have misunderstood your issue.
Can you explain this in a bit more details?

Please also do note that, from my point of view (I'm no maintainer), this project is not there to copy 100% of the NotifyIcon functionality 100%. It should bring you a much nicer experience and allow you to use WPF.

I myself would not like it when a context menu is closed just because the mouse pointer moves to a different position.

P.S.
The following remark is about the last sentence in your comment "Please fix this ASAP".
I'm not sure if you ever tried to maintain an Open Source project, but it's not nice to push maintainers into fixing issues. Open Source is provided "as is" and should be considered a gift. The person supplying this gift to you has the right to do nothing. I have some projects myself, and hate it when people write things like that, and sometimes such remarks have the effect that their issue becomes the last on my list or depending on the tone/text or even are closed without much comment.

If it's really urgent, you are more than welcome to supply a PR. :grin:

**Comment by hardcodet** [comment] 2019-08-06 13:40
I'm closing this for now as the request is unclear. If you want us to review, please provide some more context - thanks!

**Closed by hardcodet** 2019-08-06 13:40 UTC
Labels: needs clarification
